---
version: "3.4"

services:
  peering-manager:
    &peering-manager
    image: peeringmanager/peering-manager:${VERSION-add-nokia-sros-support}
    env_file: env/peering-manager.env
    user: "unit:root"
    volumes:
      - ./startup_scripts:/opt/peering-manager/startup_scripts:z,ro
      - ./initializers:/opt/peering-manager/initializers:z,ro
      - ./configuration:/etc/peering-manager/config:z,ro
    depends_on:
      - postgres
      - redis
      - rqworker
  rqworker:
    <<: *peering-manager
    depends_on:
      - postgres
      - redis
    command:
      - /opt/peering-manager/venv/bin/python
      - /opt/peering-manager/manage.py
      - rqworker
  housekeeping:
    <<: *peering-manager
    environment:
      - COMMAND_INTERVAL=86400
    depends_on:
      - postgres
      - redis
    command:
      - /opt/peering-manager/run-command.sh
      - housekeeping
  peeringdb-sync:
    <<: *peering-manager
    environment:
      - COMMAND_INTERVAL=86400
    depends_on:
      - postgres
      - redis
    command:
      - /opt/peering-manager/run-command.sh
      - peeringdb_sync
  postgres:
    image: postgres:14-alpine
    env_file: env/postgres.env
    volumes:
      - peering-manager-data:/var/lib/postgresql/data
  redis:
    image: redis:7-alpine
    env_file: env/redis.env
    volumes:
      - peering-manager-redis:/data
    command:
      - sh
      - -c # this is to evaluate the $REDIS_PASSWORD from the env
      - redis-server --requirepass $$REDIS_PASSWORD ## $$ because of docker-compose

volumes:
  peering-manager-data:
    driver: local
  peering-manager-redis:
    driver: local
